<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EQ55Q8H" failures="1" tests="6" name="TestNg1.AssertHard" time="0.043" errors="0" timestamp="2022-06-28T17:00:26 IST" skipped="2">
  <testcase classname="TestNg1.AssertHard" name="tc6" time="0.005">
    <failure message="string must be contain something expected object to not be null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: string must be contain something expected object to not be null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.assertNotNull(Assert.java:942)
at TestNg1.AssertHard.tc6(AssertHard.java:75)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc6 -->
  <system-out/>
  <testcase classname="TestNg1.AssertHard" name="tc5" time="0.006"/>
  <system-out>
    <![CDATA[tc5 pass]]>
  </system-out>
  <testcase classname="TestNg1.AssertHard" name="tc2" time="0.003"/>
  <system-out>
    <![CDATA[tc2 pass]]>
  </system-out>
  <testcase classname="TestNg1.AssertHard" name="tc1" time="0.029"/>
  <system-out>
    <![CDATA[tc1 pass]]>
  </system-out>
  <testcase classname="TestNg1.AssertHard" name="tc3">
    <skipped/>
  </testcase> <!-- tc3 -->
  <system-out/>
  <testcase classname="TestNg1.AssertHard" name="tc4">
    <skipped/>
  </testcase> <!-- tc4 -->
  <system-out/>
</testsuite> <!-- TestNg1.AssertHard -->
